/*
Initialization = is the assignment of an initial value for a data object or variable.
The complement of initialization is finalization, which is primarily used for objects, but not variables.
Initialization is done either by statically embedding the value at compile time, or else by assignment at run time. 
Initialization code may be part of a constructor (class method) or an initializer (instance method). 

<b>Declaration</b>  = is a language construct that specifies properties of an identifier: it declares what a word (identifier) "means"
*/
